server:
  port: 8763
spring:
  application:
    name: consumer
  datasource:
    master:

    first:
      url: jdbc:mysql://172.30.198.177:3306/cstas?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
      username: root
      password: Ywzt@m2020
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      url: jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Shanghai
      username: bcy
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: http://10.231.132.83:8848
    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748
feign:
  sentinel:
    enabled: true
mybatis:
#  mapper-locations: classpath*:mybatis/*Mapper.xml #mapper文件所在位置
  type-aliases-package: com.bcy.domain #映射的实体类所在的位置
